name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  other:
    name: jobby
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2]

    steps:
      - run: test ${{ matrix.group }} = 1
