name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  good:
    runs-on: ubuntu-latest
    steps:
      - run: true

  pre:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2]
    steps:
      - run: test ${{ matrix.group }} = 1

  jobby:
    runs-on: ubuntu-latest
    needs: [pre, good]
    steps:
      - run: true
